const env = import.meta.env;

const SOLANA_URL = env.VITE_SOLANA_URL;
const NEON_CORE_API_RPC_URL = env.VITE_NEON_CORE_API_RPC_URL;
const NEON_FAUCET_URL = env.VITE_NEON_FAUCET_URL;
const SOLANA_WALLET = env.VITE_SOLANA_WALLET;
const NEON_WALLET = env.VITE_NEON_WALLET;

export {
  SOLANA_URL,
  NEON_CORE_API_RPC_URL,
  NEON_FAUCET_URL,
  SOLANA_WALLET,
  NEON_WALLET
};
