const env = import.meta.env;
const PROXY_ENV = env.VITE_PROXY_ENV;
const SOLANA_URL = env.VITE_SOLANA_URL;
const NEON_CORE_API_RPC_URL = env.VITE_NEON_CORE_API_RPC_URL;
const AIRDROP_URL = env.VITE_AIRDROP_URL;
const SOLANA_WALLET = env.VITE_SOLANA_WALLET;
const NEON_WALLET = env.VITE_NEON_WALLET;

export {
  PROXY_ENV,
  SOLANA_URL,
  NEON_CORE_API_RPC_URL,
  SOLANA_WALLET,
  NEON_WALLET,
  AIRDROP_URL
};
